Repository CaptainArbitrary/ManyJobs, pull requests merged in 2023-08, with the labels that each got.

#11 Updated CI and release automation
  .github/workflows/dispatch-make-release.yml
  .github/workflows/pr-merge-to-main.yml
  .github/workflows/pr-require-label.yml
Labels: chore

#12 Fixed CI badge and link in README
  README.md
Labels: chore

#13 Remove version labels from setup-repo-labels.sh
  .github/setup-repo-labels.sh
Labels: chore

#14 Support for Vanilla Expanded Framework
  LoadFolders.xml
  Mods/oskarpotocki.vanillafactionsexpanded.core/Patches/patch.oskarpotocki.vanillafactionsexpanded.core.xml
  README.md
Labels: feature

#15 Support for Vanilla Books Expanded
  LoadFolders.xml
  Mods/vanillaexpanded.vbookse/Patches/patch.vanillaexpanded.vbookse.xml
  README.md
Labels: feature

#16 Support for Vanilla Fishing Expanded
  LoadFolders.xml
  Mods/vanillaexpanded.vcef/Patches/patch.vanillaexpanded.vcef.xml
  README.md
Labels: feature

#17 Support for Vanilla Furniture Expanded - Security
  LoadFolders.xml
  Mods/vanillaexpanded.vfesecurity/Patches/patch.vanillaexpanded.vfesecurity.xml
  README.md
Labels: feature

#18 Support for Allow Tool
  LoadFolders.xml
  Mods/unlimitedhugs.allowtool/Patches/patch.unlimitedhugs.allowtool.xml
  README.md
Labels: feature

#19 Change <author> in About.xml to CaptainArbitrary
  About/About.xml
Labels: chore

#23 Added a description to About.xml
  About/About.xml
Labels: chore

#24 More info about mods in README
  .github/README/Work_Tab_Work_Tab_lol.png
  README.md
Labels: chore

#26 Remove patches to <labelShort> and related properties
  Mods/fluffy.colonymanager/Patches/patch.fluffy.colonymanager.xml
  Mods/oskarpotocki.vanillafactionsexpanded.core/Patches/patch.oskarpotocki.vanillafactionsexpanded.core.xml
  Mods/unlimitedhugs.allowtool/Patches/patch.unlimitedhugs.allowtool.xml
  Mods/vanillaexpanded.vbookse/Patches/patch.vanillaexpanded.vbookse.xml
  Mods/vanillaexpanded.vcef/Patches/patch.vanillaexpanded.vcef.xml
Labels: chore

#27 Support for Hospitality
  LoadFolders.xml
  Mods/orion.hospitality/Patches/patch.orion.hospitality.xml
  README.md
Labels: feature

#28 Added CODEOWNERS file
  .github/CODEOWNERS
Labels: chore

#29 Added CODEOWNERS file
  .github/FUNDING.yml
Labels: chore

#31 Added new worktypes to the appropriate mechs
  1.4/Biotech/Patches/Biotech.xml
  README.md
Labels: chore

#32 Removed outdated mod references in LoadFolders.xml
  LoadFolders.xml
Labels: bug

#33 [Push] CI workflow now uploads a build artifact
  .github/workflows/push-ci.yml
Labels: chore

#37 Create steam-description.txt
  steam-description.txt
Labels: chore

#40 Updated the README and the Steam description
  README.md
  steam-description.txt
Labels: chore

#41 Patched the Core WorkTypeDefs to give them better <descriptions>
  1.4/Common/Defs/WorkTypeDefs.xml
  1.4/Core/Patches/Core.xml
Labels: bug

#44 Fixed a mild incompatibility with Recycle This by changing the mod load order
  About/About.xml
Labels: bug

#46 Replace GitHub Action workflows with rewritten ones
  .github/setup-repo.sh
  .github/workflows/ci.yml
  .github/workflows/configurations/release-changelog-builder.json
  .github/workflows/dispatch-make-release.yml
  .github/workflows/make-release.yml
  .github/workflows/pr-label.yml
  .github/workflows/pr-require-label.yml
  .github/workflows/push-ci.yml
  About/About.xml
Labels: chore

#53 Update make-release workflow to include subject in merge command
  .github/workflows/make-release.yml
Labels: chore

#54 Added support for Misc. Robots and Misc. Robots++
  LoadFolders.xml
  Mods/alaestor.miscrobots.plusplus/Patches/patch.alaestor.miscrobots.plusplus.xml
  Mods/haplo.miscellaneous.robots/Patches/patch.haplo.miscellaneous.robots.xml
Labels: feature

#57 Added Misc. Robots and Misc. Robots++ to the README as supported mods
  README.md
Labels: chore

#59 Add Discord & Ko-Fi badges to README
  README.md
Labels: chore

#60 Added support for Vanilla Factions Expanded - Mechanoids
  LoadFolders.xml
  Mods/oskarpotocki.vfe.mechanoid/Patches/patch.oskarpotocki.vfe.mechanoid.xml
Labels: feature

#61 Updated GitHub Action workflows
  .github/workflows/ci.yml
  .github/workflows/configurations/changelog-bbcode.json
  .github/workflows/configurations/changelog-github.json
  .github/workflows/configurations/changelog-md.json
  .github/workflows/configurations/changelog-txt.json
  .github/workflows/make-release.yml
Labels: chore

#68 Refactored patching worktype visibility to reduce number of patches
  1.4/Biotech/Patches/patches.biotech.xml
  1.4/Common/Patches/patch.common.xml
  1.4/Core/Patches/patches.core.xml
  1.4/Ideology/Patches/patches.ideology.xml
  Mods/alaestor.miscrobots.plusplus/Patches/patches.alaestor.miscrobots.plusplus.xml
  Mods/dubwise.dubsbadhygiene/Patches/patches.dubwise.dubsbadhygiene.xml
  Mods/fluffy.fluffybreakdowns/Patches/patches.fluffy.fluffybreakdowns.xml
  Mods/haplo.miscellaneous.robots/Patches/patches.haplo.miscellaneous.robots.xml
  Mods/oskarpotocki.vanillafactionsexpanded.core/Patches/patches.oskarpotocki.vanillafactionsexpanded.core.xml
  Mods/oskarpotocki.vfe.mechanoid/Patches/patches.oskarpotocki.vfe.mechanoid.xml
  Mods/unlimitedhugs.allowtool/Patches/patches.unlimitedhugs.allowtool.xml
  Mods/vanillaexpanded.vfesecurity/Patches/patches.vanillaexpanded.vfesecurity.xml
  Mods/weilbyte.snapout/Patches/patches.weilbyte.snapout.xml
  Source/XML/Patches/OptionalPatchExternal-template.xml
Labels: chore

#69 Added a compatibility patch for WVC - Xenotypes and Genes
  LoadFolders.xml
  Mods/wvc.sergkart.races.biotech/patch.wvc.sergkart.races.biotech.xml
Labels: feature

#71 Lifter mechanoids (Biotech) and Hauler robots (Misc. Robots/Misc. Robots++) can now do undertaking jobs
  1.4/Biotech/Patches/patches.biotech.xml
  Mods/alaestor.miscrobots.plusplus/Patches/patches.alaestor.miscrobots.plusplus.xml
  Mods/haplo.miscellaneous.robots/Patches/patches.haplo.miscellaneous.robots.xml
Labels: enhancement

#75 Remove CarryToGeneExtractor from MJobs_Mechanitor
  1.4/Biotech/Patches/patches.biotech.xml
Labels: bug

#76 Update the workType of some Biotech work givers
  1.4/Biotech/Patches/patches.biotech.xml
Labels: enhancement

#93 Added support for Vanilla Ideology Expanded - Memes and Structures
  LoadFolders.xml
  Mods/vanillaexpanded.vmemese/Patches/patch.vanillaexpanded.vmemese.xml
Labels: feature

#95 Added support for Alpha Biomes
  LoadFolders.xml
  Mods/sarg.alphabiomes/Patches/patch.sarg.alphabiomes.xml
Labels: feature

#99 Added support for Gene Extractor Tiers
  LoadFolders.xml
  Mods/redmattis.geneextractor/Patches/patch.redmattis.geneextractor.xml
Labels: feature

#100 Update PR label workflow concurrency cancellation
  .github/workflows/pr-label.yml
Labels: chore

#101 70 Add support patch for Tiered Mechs
  LoadFolders.xml
  Mods/pyro.tieredmechs/Patches/patch.pyro.tieredmechs.xml
Labels: feature

#103 Added support for Vanilla Brewing Expanded and the Coffee and Tea add-on
  LoadFolders.xml
  Mods/vanillaexpanded.vbrewe/Patches/patch.vanillaexpanded.vbrewe.xml
  Mods/vanillaexpanded.vbrewecandt/Patches/patch.vanillaexpanded.vbrewecandt.xml
Labels: feature

#105 Improved support for Vanilla Factions Expanded - Mechanoids
  Mods/oskarpotocki.vfe.mechanoid/Patches/patches.oskarpotocki.vfe.mechanoid.xml
Labels: enhancement

#106 Added support for Vanilla Plants Expanded - More Plants
  LoadFolders.xml
  Mods/vanillaexpanded.vplantsemore/Patches/patch.vanillaexpanded.vplantsemore.xml
Labels: feature

#108 Added support for Vanilla Races Expanded - Sanguophage
  LoadFolders.xml
  Mods/vanillaracesexpanded.sanguophage/Patches/patch.vanillaracesexpanded.sanguophage.xml
Labels: feature

#109 Added support for Vehicle Framework
  LoadFolders.xml
  Mods/smashphil.vehicleframework/Patches/patch.smashphil.vehicleframework.xml
Labels: feature

#112 Update screenshot to show Grouped Pawns Lists + Compact Work Tab
  .github/README/Work_Tab_Work_Tab_lol.png
Labels: chore
